apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: murgdur
spec:
  replicas: 2
  selector:
    matchLabels: { app: pgbouncer }
  template:
    metadata:
      labels: { app: pgbouncer }
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:latest
          ports:
            - containerPort: 5432
